# Generated by Django 5.0.6 on 2024-09-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='idCategoria')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='DeporteD',
            fields=[
                ('idDeporte', models.AutoField(db_column='idDeporte', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre')),
                ('horario', models.FloatField(verbose_name='horario')),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deportes.categoria', verbose_name='idCategoria')),
            ],
        ),
    ]
