# Generated by Django 5.0.6 on 2024-09-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociosCuota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociocuota',
            old_name='imp',
            new_name='importe',
        ),
    ]
