# Generated by Django 5.0.6 on 2024-09-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociosCuota', '0002_rename_imp_sociocuota_importe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociocuota',
            old_name='importe',
            new_name='imp',
        ),
    ]
